### ISSUE TITLE
Feature request: Keep old tranlations when id being removed

### ISSUE THREAD

**Issue by ratson** [GertjanReynaert/react-intl-translations-manager#29]
This would be useful when some id was removed and later added back, old translation could be restored instead of losing them.

**Comment by GertjanReynaert** [comment]
While I agree this would be helpful, I don't see a clear way of implementing this kind of functionality, since you don't really have a distinction between `really` deleting an id and `temporarily` deleting an id.

Keeping all deleted ids doesn't seems good to me either, because you then will have an ever growing translations file including translations that aren't used anymore.

If you want to give this a try, I'm willing to accept a pull request, but for now I'm going to close this issue.

**Comment by ratson** [comment]
I was thinking to provide an option for user to choose storing the old translations. If the old translations become too big / useless, user could delete them at will, instead of losing them after extraction.

You may refer to https://github.com/i18next/i18next-parser on how it is implemented. I wish I have time to help on this.
