### ISSUE TITLE
output .js instead of .json and add description and additional info as comments 

### ISSUE THREAD

**Issue by Ognian** [GertjanReynaert/react-intl-translations-manager#35]
Hi,
thanks for this great plugin.
I think that this (output .js instead of .json and add description and additional info as comments) would solve the problem to have to look into 2 different files. And since there are no comments in json we can use js instead :-).
see also https://github.com/yahoo/react-intl/issues/461 where I also suggest to combine react-intl-translations-manager  into babel-plugin-react-intl.
Thanks a lot
Ognian

**Comment by GertjanReynaert** [comment]
Sorry but I'll keep the json output instead of using javascript output. This because of a number of reasons:

1. Its a more universal format for storing data than javascript (The translations are data, not code)
2. Its easier for other applications to read in json instead of javascript
3. Its an easier format to write away to a file

If you still want this javascript output, feel free to implement it based on the core of this package.

On merging this package with the babel-plugin-react-intl: this most likely won't happen. The `babel-plugin-react-intl` packages sole purpose is exporting all messages from your project. Hereby they don't want to force you onto using a tool for managing your translations. This translation manager is one option, but without merging both packages you still would have the option to use another tool for managing your translations
