### ISSUE TITLE
[request] add support for message directory array

### ISSUE THREAD

**Issue by rjma** [GertjanReynaert/react-intl-translations-manager#37]
Can we have multiple directory patterns to support like this ?

 messagesDirectory: ['src1', 'src2']

**Comment by GertjanReynaert** [comment]
Hm, not sure why you would need this, since the `babel-plugin-react-intl` exports to a single folder

**Comment by rjma** [comment]
I have a project which compiles to multiple applications. the code are organized like this:
-src
--common
--app1
--app2

babel-plugin-react-intl process the whole src folder, which is good. But I want to merge the json separately for app1, app2. Then, it would be good to config messagesDirectory as ['common', 'app1'] and ['common', 'app2'].

**Comment by GertjanReynaert** [comment]
Sorry for the late response. If I understand correctly you want to do something similar to code splitting but then with your translation files.

I currently don't need this functionality, and since this is already pretty advanced and not frequently requested, I don't want to add this to the default translation manager. You can always try to create this kind of functionality based on the translation managers internals. If you need some help with the internals I can always assist you with that.
