### ISSUE TITLE
How to handle defaultMessage and translation being the same

### ISSUE THREAD

**Issue by txix** [GertjanReynaert/react-intl-translations-manager#38]
Hello,

Awesome plugin!

I'm wondering how to handle the following scenario:

A defaultMessage of 'Videos' has a dutch(NL) translation of 'Videos'.

When I run the manage translation command, it will tell you that Videos is untranslated.

This is probably because it's the same as the defaultMessage? Is there something I can do about this?

**Comment by GertjanReynaert** [comment]
Whitelists to the rescue!

Not sure if you already noticed but together with your `nl.json` there should be a `whitelist_nl.json` file created. Here you can put the message key in the array, and that message will no longer show up in the untranslated messages. If for some reason you change the translation, running the manager will automatically remove the key from the whitelist, because it detects the translation and default are different.

You can check the `whitelistDirectory` part of the [config documentation](https://github.com/GertjanReynaert/react-intl-translations-manager#config)

**Comment by txix** [comment]
Wow. Pardon me for missing that. My question is exactly being answered in that part of the documentation, guess I overlooked.

Thanks for the quick answer. :)

**Comment by chapati23** [comment]
maybe i'm using this wrong then.

for my default locale "en", the defaultMessages are basically the translations already. so the translations file will always equal the defaultMessages and hence cause a `Untranslated Key` warning for every single key.

what'd be a way to mitigate this? have my [translate-aggregator](https://github.com/yahoo/react-intl/blob/master/examples/translations/scripts/translate.js#L13-L26) automatically generate a corresponding whitelist file for my default locale?

**Comment by pulse00** [comment]
> for my default locale "en", the defaultMessages are basically the translations already

@chapati23 have you found a solution for this?
