### ISSUE TITLE
I've cloned the repository and tried the example but it compiles to empty translations

### ISSUE THREAD

**Issue by cloud-walker** [GertjanReynaert/react-intl-translations-manager#49]
I've `npm install` both root folder and example folder, then on root folder i've `npm run build` and then on example folder i've `npm run manage:translations`.

The results are locale json with no translations inside, just empty arrays/objects.

I'm missing something?

**Comment by GertjanReynaert** [comment]
You should run `npm run build` in both the root folder as in the example.

The example uses the local build of the translation manager so that's why you need to `npm run build` in the root folder.

Running the `npm run build` script in the example is necessary to let the `babel-plugin-react-intl` plugin extract the messages out of your application. When you run the `manage:translations` script the translation manager will use the resulting output of the babel plugin.

Since you didn't ran a build of the example, there weren't any messages extracted, and thus will the translation manager just create empty files.
