### ISSUE TITLE
how do you auto update english (en locale) translation

### ISSUE THREAD

**Issue by craigcosmo** [GertjanReynaert/react-intl-translations-manager#58]
In the translatetionRunner file I have two locales in the languages section

```js
manageTranslations({
  messagesDirectory: 'dist/message',
  translationsDirectory: 'dist/translation',
  languages: ['en', 'sv'] 
});
```

The defeault message in my component looks like below

registerFormComponent.js
```js
const messages = defineMessages({
	name: {
		id: 'registerForm.name',
		defaultMessage: 'full name'
	},
	email:{
		id: 'registerForm.email',
		defaultMessage: 'email address'
	}
});
```

Now, when I run the translatetionRunner file. I will have the outputs like this

en.json

```json
{
  "registerForm.email": "full name",
  "registerForm.name": "email"
}
```

sv.json

```json
{
  "registerForm.email": "full name",
  "registerForm.name": "email"
}
```

That's fair use case. Now I want to change the default message in registerFormComponent.js. I will change value 'full name' to 'your name'. Then I run the translation runner again. What I expect is. The sv.json will stay intact, but the en.json now will autoupdate.

The en.json now should automatically look like this

```json
{
  "registerForm.email": "your name",
  "registerForm.name": "email"
}
```

Hope that make sense about what I want to do. Just asking if this is possible?

**Comment by GertjanReynaert** [comment]
Auto updating in the generated files isn't possible.

The translation manager will only point out what translations are currently missing, so it wont update your translation files, except for adding new translations.

By your example I deduct that `en` is the default language of your application. Since these translations are managed in your components, these don't need to be managed by the translation manager.

I would suggest removing `en` from your languages to manage. This will also stop adding new translations to `en.json`, so I would suggest removing that file as well. If you want to extract your default messages into a separate file, you can always use the [`singleMessagesFile`](https://github.com/GertjanReynaert/react-intl-translations-manager#config) option.

I hope this helps, if you still have any questions, please do not hesitate to ask

**Comment by craigcosmo** [comment]
that makes sense, thanks.
