### ISSUE TITLE
Detect unused translations

### ISSUE THREAD

**Issue by maniax89** [GertjanReynaert/react-intl-translations-manager#74]
I had mentioned this over in a https://github.com/yahoo/babel-plugin-react-intl/issues/86

Would be nice if a translations manager could also detect unused translations and mark them for removal. I am not sure what the best way to approach this is at the moment and was wondering if it has been considered.

**Comment by GertjanReynaert** [comment]
Hm, since `react-intl-translations-manager` is just a tool on top of `babel-plugin-react-intl`, this plugin can only leverage babel-plugin-react-intl's powers. Unfortunately this isn't something we can do right now.

Maybe with future versions of `react-intl` or `babel-plugin-react-intl` this becomes possible, but until then I'll close this issue.
