### ISSUE TITLE
Merge custom translations files: feature request

### ISSUE THREAD

**Issue by pbreah** [GertjanReynaert/react-intl-translations-manager#85]
The use case is this:

Let's say I have my React components already translated, and the react-intl-translations-manager picks up all the json files generated from babel-plugin-react-intl - which is what we expect. But let's say I need to manage translations that are not on the component themselves, because these are stored on the database.

Since these translations are stored on the database, the babel-plugin-react-intl cannot pull these messages, and react-intl-translations-manager wouldn't know about these either.

So what I propose is to have an option that would allow to merge a custom translations json file with  messages (that babel-plugin-react-intl wll not be able to know about) that would be merged into the locale files generated by react-intl-translations-manager.

That way I can easily perform translations for messages that are stored on the database, and not directly on components.

Ideas?

**Comment by Meroje** [comment]
That already works as you explained, any json file in your messages directory will be picked up.

**Comment by pbreah** [comment]
I understand that json files on the messages directory get picked up - but since this directory is constantly re-generated and if on your deployment process you delete this directory, it wouldn't be a good place for your custom json files to be.

I guess the option could be as simple as having another path to pickup and merge json files from - not being the messages directory that may be deleted after each deployment.

**Comment by GertjanReynaert** [comment]
@pbreah Actually @Meroje is correct.

I do get that your messages folder is constantly being regenerated, but since the messages in that folder are also nested, the React-intl-translation-manager will recursively use all files in the messages folder you specified.

So If you configure the translation manager to use a certain folder (example `messages`), and then you have a subfolder with database translations (example: `databaseMessages`) and a subfolder with extracted messages (example: `extractedMessages`) that is being regenerated, everything should work

```
- messages
  |
  +- databaseMessages
  +- extractedMessages
```
