### ISSUE TITLE
Add licence information

### ISSUE THREAD

**Issue by dezoxel** [GertjanReynaert/react-intl-translations-manager#90]
Hello everyone,

We have restrictions on our project using 3rd-party npm modules. We can't use them if license is not specified. I would really like to use translations manager thus I'm submitting a request to add license information to the README and put LICENSE file to the project root.

If you prefer I can create a PR for that purpose but I need to verify the licence type first.

Thanks!

**Comment by cameron-martin** [comment]
the package.json specifies the license as MIT.

**Comment by GertjanReynaert** [comment]
@dezoxel as @cameron-martin correctly pointed out, this project uses the MIT license. Since this is only mentioned in the package.json file, I'm definitely open to a PR with a license file.

Maybe something similar to what github does in their [hubot](https://github.com/github/hubot) repo? Small mention in the readme, and separate `LICENSE.md` file

**Comment by dezoxel** [comment]
@GertjanReynaert thank you!
